require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/program_streams', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ProgramStream. As you add validations to ProgramStream, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      ProgramStream.create! valid_attributes
      get program_streams_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      program_stream = ProgramStream.create! valid_attributes
      get program_stream_url(program_stream)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_program_stream_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      program_stream = ProgramStream.create! valid_attributes
      get edit_program_stream_url(program_stream)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ProgramStream' do
        expect do
          post program_streams_url, params: { program_stream: valid_attributes }
        end.to change(ProgramStream, :count).by(1)
      end

      it 'redirects to the created program_stream' do
        post program_streams_url, params: { program_stream: valid_attributes }
        expect(response).to redirect_to(program_stream_url(ProgramStream.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ProgramStream' do
        expect do
          post program_streams_url, params: { program_stream: invalid_attributes }
        end.to change(ProgramStream, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post program_streams_url, params: { program_stream: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested program_stream' do
        program_stream = ProgramStream.create! valid_attributes
        patch program_stream_url(program_stream), params: { program_stream: new_attributes }
        program_stream.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the program_stream' do
        program_stream = ProgramStream.create! valid_attributes
        patch program_stream_url(program_stream), params: { program_stream: new_attributes }
        program_stream.reload
        expect(response).to redirect_to(program_stream_url(program_stream))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        program_stream = ProgramStream.create! valid_attributes
        patch program_stream_url(program_stream), params: { program_stream: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested program_stream' do
      program_stream = ProgramStream.create! valid_attributes
      expect do
        delete program_stream_url(program_stream)
      end.to change(ProgramStream, :count).by(-1)
    end

    it 'redirects to the program_streams list' do
      program_stream = ProgramStream.create! valid_attributes
      delete program_stream_url(program_stream)
      expect(response).to redirect_to(program_streams_url)
    end
  end
end
